### ISSUE TITLE
Scalability of video reference management

### ISSUE THREAD

**Issue by ad-m** [amitness/papers-with-video#2]
Hello,

I would like ask what is plan and goal regarding scaling article-video mapping? In-code mapping looks pretty in-efficient. 

The first step could be to extract this into a separate JSON file.

I checked YouTube video search performance and surprisingly relevant results:

```http
GET https://youtube.googleapis.com/youtube/v3/search?part=snippet&q=2002.04599&key=[YOUR_API_KEY] HTTP/1.1

Authorization: Bearer [YOUR_ACCESS_TOKEN]
Accept: application/json
----
HTTP/1.1 200 OK
cache-control: private
content-encoding: gzip
content-length: 627
content-type: application/json; charset=UTF-8
date: Thu, 21 Jan 2021 01:56:43 GMT
server: scaffolding on HTTPServer2
vary: Origin, X-Origin, Referer

{
  "kind": "youtube#searchListResponse",
  "etag": "s14gqoKSKGiqG4t4kqPe6YQOAJg",
  "regionCode": "PL",
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  },
  "items": [
    {
      "kind": "youtube#searchResult",
      "etag": "tuQnlvn_4UeELQZ5QLYBK0iTiVk",
      "id": {
        "kind": "youtube#video",
        "videoId": "NhZY2tnDTZg"
      },
      "snippet": {
        "publishedAt": "2020-08-30T15:03:15Z",
        "channelId": "UCPSicHM25H1i7u91C8-AdAA",
        "title": "Fundamental Tradeoffs between Invariance and Sensitivity to Adversarial Perturbations",
        "description": "In this video we go over the distinction between invariance and sensitivity based adversarial perturbations. The former being a much less studied attack which is ...",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/NhZY2tnDTZg/default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/NhZY2tnDTZg/mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/NhZY2tnDTZg/hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": "Federico Barbero",
        "liveBroadcastContent": "none",
        "publishTime": "2020-08-30T15:03:15Z"
      }
    }
  ]
}
```

Maybe we should query the API when entering an article, rather than keeping our own database that needs to be maintained and is prone to overlooking. If the automatic search results are weak, we can think about using them to automatically update the database through manual review, which will avoid overlooking.

Kind regards

**Comment by amitness** [comment]
@ad-m Thank you for the suggestions.
1. I have decoupled the mapping data to a separate JSON file now. It loads the JSON file now instead of in-line hardcoding.

> I would like ask what is plan and goal regarding scaling article-video mapping?

The current mapping is not created manually. It's fully automated using Python by fetching publicly releases conference videos this year and mapping them to arxiv via [pyarxiv](https://pypi.org/project/pyarxiv/).

Using youtube API is a good idea. But, the problem is that it's not scalable to manually review each paper-video pair.
